# Generated by Django 5.0.1 on 2024-01-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0008_remove_useritem_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
