# Generated by Django 5.0.1 on 2024-01-27 03:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0009_useritem_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userItem',
            new_name='UserProduct',
        ),
    ]
