# Generated by Django 3.2.23 on 2024-01-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0010_rename_useritem_userproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.DeleteModel(
            name='UserProduct',
        ),
    ]
